config/routes.rb
Budget::Application.routes.draw do
  root to: 'reports/monthly_budget#show'

  get 'review', to: "review#index"
  scope path: 'review' do
    resources :accounts, controller: "importable_accounts", as: "importable_account", only: %i(show update)
    resources :transactions, controller: "importable_transactions", as: "importable_transaction", only: %i(show update)
  end

  resources :transactions, only: %i(index edit update) do
  end

  patch "/transactions/:from_id/transferize/:to_id", as: :transferize_transaction, to: "transactions#transferize"

  resources :accounts
  resources :categories

  scope path: 'reports' do
    get 'monthly-debt', to: "reports/monthly_debt#show", as: :monthly_debt_report

    scope to: "reports/monthly_cashflow#show" do
      get 'monthly-cashflow', as: :current_monthly_cashflow_report
      get 'monthly-cashflow/:year-:month', as: :monthly_cashflow_report, year: /\d{4}/, month: /\d{1,2}/
    end

    scope to: "reports/monthly_budget#show" do
      get 'monthly-budget', as: :current_monthly_budget_report
      get 'monthly-budget/:year-:month', as: :monthly_budget_report, year: /\d{4}/, month: /\d{1,2}/
    end

    scope controller: "reports/category_spending" do
      get 'category-spending', action: :index, as: :category_spending_reports
      get 'category-spending/:category_id', action: :show, as: :category_spending_report
    end
  end
end

app/controllers/importable_transactions_controller.rb
require 'transaction_factory'

class ImportableTransactionsController < ApplicationController
  include ReviewConcern

  def show
    # TODO: check if the transaction is already imported and if so render a different page
    @imported_transaction = TransactionFactory.build_with_inference_from_importable_transaction(importable_transaction)

    if @imported_transaction.new_record? || params[:duplicate] == "no"
      render 'new'
    elsif importable_transaction.imported_id && params[:reimport] != 'yes'
      render 'already_imported'
    else
      render 'duplicate'
    end
  end

  def update

    if filtered_params[:imported_id].present?
      importable_transaction.update_attribute :imported_id, filtered_params[:imported_id]
      return redirect_to next_review_url
    end

    # TODO: missing features
    # - reject (do not import)
    # - push off for later review
    @imported_transaction = (importable_transaction.expense ? Expense : Income).new(filtered_params)

    if TransactionImportService.new(importable_transaction, imported_transaction, filtered_params).call.success?
      redirect_to next_review_url
    else
      render 'new'
    end
  end

private
  attr_reader :imported_transaction
  helper_method :imported_transaction

  def filtered_params
    params.require(:transaction).permit(:imported_id, :cents, :account_id, :category_id, :date, :description, :notes)
  end
  
  def importable_transaction
    @_importable_transaction ||= ImportableTransaction.find(params[:id])
  end
  helper_method :importable_transaction

  def root_category
    @_root_category ||= importable_transaction.expense ? Category.expense : Category.income
  end
  helper_method :root_category

end

app/views/importable_transactions/already_imported.html.haml
= page_header "Already Imported"

%p.lead
  It looks like this record has already been imported, you can import it again 
  if you want.

= link_to "Next Record", review_path, class: "btn btn-success btn-lg"
.visible-xs-block
  %br
= link_to "Reimport", importable_transaction_path(importable_transaction, reimport: "yes"), class: "btn btn-danger btn-lg"

app/views/importable_transactions/duplicate.html.haml
= page_header "Duplicate transaction"

.table-responsive
  %table.table.table-bordered
    %thead
      %tr
        %th
        %th Existing
        %th Importing

    %tbody
      %tr
        %th{scope: "row"} Date
        %td= imported_transaction.date
        %td= importable_transaction.date

      %tr
        %th{scope: "row"} Account
        %td= imported_transaction.account.name
        %td= importable_transaction.account

      %tr
        %th{scope: "row"} Description
        %td= imported_transaction.description
        %td= importable_transaction.description

      %tr
        %th{scope: "row"} Amount
        %td= number_to_currency cents_to_dollars imported_transaction.signed_cents
        %td= number_to_currency cents_to_dollars importable_transaction.signed_cents

      %tr
        %th{scope: "row"} Category
        %td= imported_transaction.category.name
        %td= importable_transaction.category

.text-center
  = bootstrap_form_for importable_transaction, as: :transaction do |f|
    = f.hidden_field :imported_id, value: imported_transaction.id
    = f.submit "Verify Duplicate", class: "btn btn-success btn-lg"
    .visible-xs-block
      %br
    = link_to "Not a Duplicate", importable_transaction_path(importable_transaction, duplicate: "no"), class: "btn btn-danger btn-lg"

app/views/importable_transactions/new.html.haml
= page_header "Review new transaction"

%p.lead
  You have a newly imported transaction. Make changes below as you wish
  then click the "Verify" button to import it.

= bootstrap_form_for imported_transaction, as: :transaction, url: importable_transaction_path(importable_transaction), method: :patch do |f|
  = f.hidden_field :cents

  .row-fluid
    .span6
      = f.form_group :amount, label: {text: "Amount"} do
        %strong.form-control.read-only.amount{class: importable_transaction.expense ? "negative" : "positive"}= number_to_currency cents_to_dollars importable_transaction.signed_cents
      = f.collection_select :account_id, Account.order(:name), :id, :name, {help: "Imported from: #{importable_transaction.account}"}, {class: "select2", style: "width:100%;"}
      = f.collection_select :category_id, root_category.descendants.sort_by(&:name), :id, :name, {help: "Imported from: #{importable_transaction.category}"}, {class: "select2", style: "width:100%;"}

    .span6
      = f.text_field :date, type: "date", class: "span12"
      = f.text_field :description, class: "span12"
      = f.text_area :notes, class: "span12"

  .row-fluid
    .form-actions.span12
      = f.submit "Verify", class: "btn btn-primary"