config/routes.rb
Budget::Application.routes.draw do
  root to: 'reports/monthly_budget#show'

  get 'review', to: "review#index"
  scope path: 'review' do
    resources :accounts, controller: "importable_accounts", as: "importable_account", only: %i(show update)
    resources :transactions, controller: "importable_transactions", as: "importable_transaction", only: %i(show update)
  end

  resources :transactions, only: %i(index edit update) do
  end

  patch "/transactions/:from_id/transferize/:to_id", as: :transferize_transaction, to: "transactions#transferize"

  resources :accounts
  resources :categories

  scope path: 'reports' do
    get 'monthly-debt', to: "reports/monthly_debt#show", as: :monthly_debt_report

    scope to: "reports/monthly_cashflow#show" do
      get 'monthly-cashflow', as: :current_monthly_cashflow_report
      get 'monthly-cashflow/:year-:month', as: :monthly_cashflow_report, year: /\d{4}/, month: /\d{1,2}/
    end

    scope to: "reports/monthly_budget#show" do
      get 'monthly-budget', as: :current_monthly_budget_report
      get 'monthly-budget/:year-:month', as: :monthly_budget_report, year: /\d{4}/, month: /\d{1,2}/
    end

    scope controller: "reports/category_spending" do
      get 'category-spending', action: :index, as: :category_spending_reports
      get 'category-spending/:category_id', action: :show, as: :category_spending_report
    end
  end
end

app/controllers/reports/category_spending_controller.rb
module Reports
  class CategorySpendingController < ApplicationController

    def index
      @income_categories = Category.income.descendants.order(:name)
      @expense_categories = Category.expense.descendants.order(:name)
    end

    def show
      @category = Category.find(params[:category_id])
      @report = CategoricalSpendingReport.new(@category)
    end

  end
end

app/controllers/reports/monthly_budget_controller.rb
require 'month_enumerator'

module Reports
  class MonthlyBudgetController < ApplicationController

    def show
      @report = MonthlyBudgetReport.new(time)
    end

  private
    YearMonth = Struct.new(:year, :month) do
      def value
        "#{year}-#{month}"
      end

      def text
        Time.local(year, month, 1, 0, 0, 0).strftime("%B %Y")
      end
    end

    def selected_year
      params.fetch(:year, Time.now.year).to_i
    end
    helper_method :selected_year

    def selected_month
      params.fetch(:month, Time.now.month).to_i
    end
    helper_method :selected_month

    def time
      Time.local(selected_year, selected_month, 1, 0, 0, 0)
    end
    helper_method :time

    def selectable_periods
      MonthEnumerator.since_first_transaction.map {|y,m| YearMonth.new(y,m) }.reverse
    end
    helper_method :selectable_periods

  end
end

app/controllers/reports/monthly_cashflow_controller.rb
require 'month_enumerator'

module Reports
  class MonthlyCashflowController < ApplicationController

    def show
      @report = MonthlyCashflowReport.new(time)
      @debt = MonthlyDebtReport.new(time)
    end

  private
    YearMonth = Struct.new(:year, :month) do
      def value
        "#{year}-#{month}"
      end

      def text
        Time.local(year, month, 1, 0, 0, 0).strftime("%B %Y")
      end
    end

    def selected_year
      params.fetch(:year, Time.now.year).to_i
    end
    helper_method :selected_year

    def selected_month
      params.fetch(:month, Time.now.month).to_i
    end
    helper_method :selected_month

    def time
      Time.local(selected_year, selected_month, 1, 0, 0, 0)
    end
    helper_method :time

    def selectable_periods
      MonthEnumerator.since_first_transaction.map {|y,m| YearMonth.new(y,m) }.reverse
    end
    helper_method :selectable_periods

  end
end

app/controllers/reports/monthly_debt_controller.rb
require 'month_enumerator'
require 'csv'

module Reports
  class MonthlyDebtController < ApplicationController

    def show
      respond_to do |format|
        format.html
        format.csv { render text: to_csv }
      end
    end

  private

    def to_csv
      CSV.generate do |csv|
        csv << %w(month net total)
        months.each {|row| csv << row }
      end
    end

    def months
      MonthEnumerator.since_first_transaction.map do |year, month|
        time = Time.local(year, month, 1,  0, 0, 0)
        
        stamp = (time.utc.to_f * 1000).to_i

        net_diff = MonthlyDebtReport.new(time).net_income / 100.0

        [stamp, net_diff]
      end.inject([]) do |rows, nxt|
        nxt << rows.map(&:second).sum + nxt.last

        rows << nxt
      end
    end

  end
end

app/views/reports/category_spending/_group.html.haml
%h3= title
%table.table.table-striped
  %tbody
    - entries.each do |entry|
      %tr
        %td.col-md-12= link_to entry.name, category_spending_report_path(entry)

app/views/reports/category_spending/index.html.haml
= render "reports/category_spending/group", title: "Income", entries: @income_categories
= render "reports/category_spending/group", title: "Expenses", entries: @expense_categories

app/views/reports/category_spending/show.html.haml
.page-header
   - if @category.expense?
      %h1 Spending for #{@category.name}
   - else
      %h1 Income for #{@category.name}

%div
   %strong Monthly Average:
   = number_to_currency(cents_to_dollars(@report.monthly_average))

%table.table.table-striped
   %thead
      %tr
         %th Month
         %th Spent
   %tbody
      - @report.groups.reverse.each do |group|
         %tr
            %td.col-md-6= link_to group.start_of_period.strftime("%B %Y"), transactions_path(q: {date_gteq: group.start_of_period.strftime("%Y-%m-%d"), date_lteq: group.end_of_period.strftime("%Y-%m-%d"), category_id_eq: @category.id})
            %td.col-md-6.amount= number_to_currency(cents_to_dollars(group.cents), unit: "")