config/routes.rb
Budget::Application.routes.draw do
  root to: 'reports/monthly_budget#show'

  get 'review', to: "review#index"
  scope path: 'review' do
    resources :accounts, controller: "importable_accounts", as: "importable_account", only: %i(show update)
    resources :transactions, controller: "importable_transactions", as: "importable_transaction", only: %i(show update)
  end

  resources :transactions, only: %i(index edit update) do
  end

  patch "/transactions/:from_id/transferize/:to_id", as: :transferize_transaction, to: "transactions#transferize"

  resources :accounts
  resources :categories

  scope path: 'reports' do
    get 'monthly-debt', to: "reports/monthly_debt#show", as: :monthly_debt_report

    scope to: "reports/monthly_cashflow#show" do
      get 'monthly-cashflow', as: :current_monthly_cashflow_report
      get 'monthly-cashflow/:year-:month', as: :monthly_cashflow_report, year: /\d{4}/, month: /\d{1,2}/
    end

    scope to: "reports/monthly_budget#show" do
      get 'monthly-budget', as: :current_monthly_budget_report
      get 'monthly-budget/:year-:month', as: :monthly_budget_report, year: /\d{4}/, month: /\d{1,2}/
    end

    scope controller: "reports/category_spending" do
      get 'category-spending', action: :index, as: :category_spending_reports
      get 'category-spending/:category_id', action: :show, as: :category_spending_report
    end
  end
end

app/controllers/transactions_controller.rb
require 'transferize_policy'

class TransactionsController < ApplicationController

  def index
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def update
    @transaction = Transaction.find(params[:id])

    if @transaction.update(filtered_params)
      redirect_to params[:return_to].presence || transactions_path, notice: "Transaction updated"
    else
      render action: 'edit'
    end
  end

  def transferize
    from = Transaction.find(params[:from_id])
    to = Transaction.find(params[:to_id])

    if (reason = TransferizePolicy.new(from, to).validate) == true
      TransferizeService.new(from, to).call
      render json: {}, status: :ok
    else
      render json: {reason: reason}, status: :bad_request
    end
  end

private

  def filtered_params
    params.require(:transaction).permit(:category_id, :notes)
  end

  def scope
    Transaction.order("date desc, cents desc, type desc, id asc").includes(:account, :category)
  end

  def query
    @query ||= scope.ransack(params[:q])
  end
  helper_method :query

  def collection
    query.result.page(params.fetch(:page, 1)).per(50)
  end
  helper_method :collection

  def root_category
    @_root_category ||= @transaction.is_a?(Expense) ? Category.expense : Category.income
  end
  helper_method :root_category

end

app/views/transactions/edit.html.haml
= page_header "Edit transaction"

= bootstrap_form_for @transaction, as: :transaction, url: transaction_path(@transaction) do |f|
  = hidden_field_tag :return_to, params[:return_to]

  %div
    = f.collection_select :category_id, root_category.descendants.sort_by(&:name), :id, :name, {}, {class: "select2", style: "width:100%"}

  %div
    = f.text_area :notes, class: "span12"

  .row-fluid
    .form-actions.span12
      = f.submit "Update", class: "btn btn-primary"

app/views/transactions/index.html.haml
= page_header "Transactions"

#search
  = search_form_for query, class: "form-inline" do |f|
    = f.date_field :date_gteq, placeholder: "from", class: "form-control"
    = f.date_field :date_lteq, placeholder: "to", class: "form-control"
    = select_tag "q[category_id_eq]", grouped_options_for_income_and_expenses(params.fetch(:q, {}).fetch(:category_id_eq, nil)), include_blank: true, class: "form-control"
    = f.collection_select :account_id_eq, Account.all, :id, :name, {include_blank: true}, class: "form-control"

  .pull-right
    = link_to "Make Transfer", transferize_transaction_path(":from_id", ":to_id"), id: "transferize", class: "btn btn-danger"

%table#transactions.table.table-striped
  %thead
    %tr
      %td.span1
      %td Date
      %td Description
      %td Amount
      %td Category
      %td Account

  %tbody
    - collection.each do |t|
      %tr{id: "transaction-#{t.id}", data: {id: t.id}}
        %td.span1= check_box_tag ""
        %td.span2= t.date.to_s
        %td= link_to t.description, edit_transaction_path(t, return_to: request.url)
        %td.span2.amount{class: t.is_a?(Expense) ? "negative" : "positive"}= number_to_currency(cents_to_dollars(t.cents), unit: "")
        %td= t.category.name
        %td.span2= t.account.name

.row-fluid
  .span12.text-center= paginate collection, theme: "twitter-bootstrap-3"